### ISSUE TITLE
Colocar uma função nova em correlation

### ISSUE THREAD

**Issue by aclorena** [lpfgarcia/ECoL#54]
Olá Luis, estou mexendo aqui no artigo enquanto o pessoal não me entrega os trabalhos para correção. Aí me ocorreu de colocarmos uma função C1 em correlation.R. Ela calcularia a correlação entre todas as features de entrada de um conjunto de dados, então serviria para classificação ou regressão. Algo do tipo as.numeric(abs(stats::cor(x, method="spearman"))).

**Comment by lpfgarcia** [comment]
r.C1 included as correlation measure
next step is evaluate the adaptation for classification problems
