### ISSUE TITLE
The implementation of enn is different from enn described in the paper?

### ISSUE THREAD

**Issue by xiong-peiyu** [lpfgarcia/ECoL#61]
Hi Dear Authors, 

Thank you for making this implementation publicly available! 
I have a question regarding the implementation of `enn` function in "network.R" file. In the paper, you mentioned "two nodes i and j are connected only if `dist(i,j) < e`, but in the implementation, I noticed the nodes connected to node i were sorted by their distances to node i and take the top e% of them (i.e. line 130 `a <- names(sort(dst[i,])[1:e+1])`) for further pruning, I was wondering if this difference is by choice or by accident? 

Thank you for your time! 

Best Regards,
Peiyu

**Comment by lpfgarcia** [comment]
Sorry for the delay. The ϵ-NN is a variation of the k-NN. While k represents the number of samples nearest neighbors, the ϵ is the percentage of samples nearest neighbors. In other words, d(i,j) < ϵ means the ϵ percentage of samples in the dataset with the lowerest distances.
